export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  COURSES: "/courses",
  INSTRUCTORS: "/instructors",
  ABOUT: "/about",
  CONTACT: "/contact",
  DASHBOARD: "/dashboard",
  TERMS: "/terms",
  PRIVACY: "/privacy",
  SERVICES: "/services",
  BECOME_INSTRUCTOR: "/become-instructor",
  CART: "/cart",
  CHECKOUT: "/checkout",
  ORDER_SUCCESS: "/order-success",
  PAYMENT_STATUS: "/payment/status",
  COURSE_DETAILS: "/courses/:id",
  LESSON: "/courses/:courseId/lessons/:lessonId",
  INSTRUCTOR_DETAILS: "/instructors/:id",
} as const;
